server:
  port: 8420
  error:
    path: /error
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  server:
    port: 8421
spring:
  main:
    web-application-type: reactive
  reactor:
    debug-agent:
      enabled: true
  webflux:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  data:
    mongodb:
      database: userme
      port: 27017
      host: localhost
      username: userme_db_admin
      password: userme_db_admin_pass
  application:
    name: USErME
    admin:
      enabled: true
  banner:
    location: static/banner-ascii-art.txt